version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ~/.kube:/root/.kube:ro
      # Αν το αρχείο /etc/rancher/k3s/k3s.yaml υπάρχει στο host σου, κάνε το mount:
      # - /etc/rancher/k3s/k3s.yaml:/root/.kube/k3s.yaml:ro
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KUBE_CONFIG_PATH=/root/.kube/config

  frontend:
    build:
      context: ./UI/cloud-native-iot
    ports:
      - "5173:80"
    depends_on:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"